@startuml
class Client {
}
class Component {
operation()
add(component)
remove(component)
getChild(i)
}
Client --right> Component
class Leaf {
operation()
}
Leaf --up|> Component
class Composite {
add(component)
remove(component)
getChild(i)
operation()
}
Composite --up|> Component
Composite --up> Component
@enduml