@startuml
class Singleton{
- Singleton instance;
- Singleton()
+ Singleton getInstance()
}
Singleton o--> Singleton : instance
note "if(instance == null) instance = new Singleton();\n return instance" as N1
Singleton --> N1
@enduml
