@startuml
class Client {
}
class Receiver {
action()
}
Client --right> Receiver
Client --right> ConcreteCommand

class Invoker {
setCommand()
}
interface Command {
execute()
undo()
}
Invoker --right> Command
class ConcreteCommand {
execute()
undo()
}
ConcreteCommand ..right|> Command
@enduml